sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mchiuminatto/recipee -f Dockerfile.dev .

script:
  - docker run -e CI=true mchiuminatto/recipee npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-259309620747"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY